/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppChannelsIndexRouteImport } from './routes/_app/channels/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminWebhookLogsRouteImport } from './routes/_app/admin/webhook-logs'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSmsQueueRouteImport } from './routes/_app/admin/sms-queue'
import { Route as AppAdminSmsLogsRouteImport } from './routes/_app/admin/sms-logs'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminEmailTransportsRouteImport } from './routes/_app/admin/email-transports'
import { Route as AppAdminEmailLogsRouteImport } from './routes/_app/admin/email-logs'
import { Route as AppAdminConnectionLogsRouteImport } from './routes/_app/admin/connection-logs'
import { Route as AppAdminApiKeysRouteImport } from './routes/_app/admin/api-keys'
import { Route as AppChannelsChannelIdIndexRouteImport } from './routes/_app/channels/$channelId/index'
import { Route as AppChannelsChannelIdSettingsRouteImport } from './routes/_app/channels/$channelId/settings'
import { Route as AppChannelsChannelIdChatContactNumberRouteImport } from './routes/_app/channels/$channelId/chat/$contactNumber'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsIndexRoute = AppChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminWebhookLogsRoute = AppAdminWebhookLogsRouteImport.update({
  id: '/webhook-logs',
  path: '/webhook-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSmsQueueRoute = AppAdminSmsQueueRouteImport.update({
  id: '/sms-queue',
  path: '/sms-queue',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSmsLogsRoute = AppAdminSmsLogsRouteImport.update({
  id: '/sms-logs',
  path: '/sms-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmailTransportsRoute = AppAdminEmailTransportsRouteImport.update({
  id: '/email-transports',
  path: '/email-transports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmailLogsRoute = AppAdminEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConnectionLogsRoute = AppAdminConnectionLogsRouteImport.update({
  id: '/connection-logs',
  path: '/connection-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApiKeysRoute = AppAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppChannelsChannelIdIndexRoute =
  AppChannelsChannelIdIndexRouteImport.update({
    id: '/channels/$channelId/',
    path: '/channels/$channelId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppChannelsChannelIdSettingsRoute =
  AppChannelsChannelIdSettingsRouteImport.update({
    id: '/channels/$channelId/settings',
    path: '/channels/$channelId/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppChannelsChannelIdChatContactNumberRoute =
  AppChannelsChannelIdChatContactNumberRouteImport.update({
    id: '/channels/$channelId/chat/$contactNumber',
    path: '/channels/$channelId/chat/$contactNumber',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/docs': typeof AppDocsRoute
  '/profile': typeof AppProfileRoute
  '/admin/api-keys': typeof AppAdminApiKeysRoute
  '/admin/connection-logs': typeof AppAdminConnectionLogsRoute
  '/admin/email-logs': typeof AppAdminEmailLogsRoute
  '/admin/email-transports': typeof AppAdminEmailTransportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/sms-logs': typeof AppAdminSmsLogsRoute
  '/admin/sms-queue': typeof AppAdminSmsQueueRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/webhook-logs': typeof AppAdminWebhookLogsRoute
  '/admin/': typeof AppAdminIndexRoute
  '/channels/': typeof AppChannelsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/channels/$channelId/settings': typeof AppChannelsChannelIdSettingsRoute
  '/channels/$channelId/': typeof AppChannelsChannelIdIndexRoute
  '/channels/$channelId/chat/$contactNumber': typeof AppChannelsChannelIdChatContactNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/docs': typeof AppDocsRoute
  '/profile': typeof AppProfileRoute
  '/admin/api-keys': typeof AppAdminApiKeysRoute
  '/admin/connection-logs': typeof AppAdminConnectionLogsRoute
  '/admin/email-logs': typeof AppAdminEmailLogsRoute
  '/admin/email-transports': typeof AppAdminEmailTransportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/sms-logs': typeof AppAdminSmsLogsRoute
  '/admin/sms-queue': typeof AppAdminSmsQueueRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/webhook-logs': typeof AppAdminWebhookLogsRoute
  '/admin': typeof AppAdminIndexRoute
  '/channels': typeof AppChannelsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/channels/$channelId/settings': typeof AppChannelsChannelIdSettingsRoute
  '/channels/$channelId': typeof AppChannelsChannelIdIndexRoute
  '/channels/$channelId/chat/$contactNumber': typeof AppChannelsChannelIdChatContactNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/docs': typeof AppDocsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/admin/api-keys': typeof AppAdminApiKeysRoute
  '/_app/admin/connection-logs': typeof AppAdminConnectionLogsRoute
  '/_app/admin/email-logs': typeof AppAdminEmailLogsRoute
  '/_app/admin/email-transports': typeof AppAdminEmailTransportsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/sms-logs': typeof AppAdminSmsLogsRoute
  '/_app/admin/sms-queue': typeof AppAdminSmsQueueRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/webhook-logs': typeof AppAdminWebhookLogsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/channels/': typeof AppChannelsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/channels/$channelId/settings': typeof AppChannelsChannelIdSettingsRoute
  '/_app/channels/$channelId/': typeof AppChannelsChannelIdIndexRoute
  '/_app/channels/$channelId/chat/$contactNumber': typeof AppChannelsChannelIdChatContactNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/docs'
    | '/profile'
    | '/admin/api-keys'
    | '/admin/connection-logs'
    | '/admin/email-logs'
    | '/admin/email-transports'
    | '/admin/settings'
    | '/admin/sms-logs'
    | '/admin/sms-queue'
    | '/admin/users'
    | '/admin/webhook-logs'
    | '/admin/'
    | '/channels/'
    | '/contacts/'
    | '/channels/$channelId/settings'
    | '/channels/$channelId/'
    | '/channels/$channelId/chat/$contactNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/docs'
    | '/profile'
    | '/admin/api-keys'
    | '/admin/connection-logs'
    | '/admin/email-logs'
    | '/admin/email-transports'
    | '/admin/settings'
    | '/admin/sms-logs'
    | '/admin/sms-queue'
    | '/admin/users'
    | '/admin/webhook-logs'
    | '/admin'
    | '/channels'
    | '/contacts'
    | '/channels/$channelId/settings'
    | '/channels/$channelId'
    | '/channels/$channelId/chat/$contactNumber'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/admin'
    | '/_app/docs'
    | '/_app/profile'
    | '/_app/admin/api-keys'
    | '/_app/admin/connection-logs'
    | '/_app/admin/email-logs'
    | '/_app/admin/email-transports'
    | '/_app/admin/settings'
    | '/_app/admin/sms-logs'
    | '/_app/admin/sms-queue'
    | '/_app/admin/users'
    | '/_app/admin/webhook-logs'
    | '/_app/admin/'
    | '/_app/channels/'
    | '/_app/contacts/'
    | '/_app/channels/$channelId/settings'
    | '/_app/channels/$channelId/'
    | '/_app/channels/$channelId/chat/$contactNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/': {
      id: '/_app/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AppChannelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/webhook-logs': {
      id: '/_app/admin/webhook-logs'
      path: '/webhook-logs'
      fullPath: '/admin/webhook-logs'
      preLoaderRoute: typeof AppAdminWebhookLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/sms-queue': {
      id: '/_app/admin/sms-queue'
      path: '/sms-queue'
      fullPath: '/admin/sms-queue'
      preLoaderRoute: typeof AppAdminSmsQueueRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/sms-logs': {
      id: '/_app/admin/sms-logs'
      path: '/sms-logs'
      fullPath: '/admin/sms-logs'
      preLoaderRoute: typeof AppAdminSmsLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/email-transports': {
      id: '/_app/admin/email-transports'
      path: '/email-transports'
      fullPath: '/admin/email-transports'
      preLoaderRoute: typeof AppAdminEmailTransportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/email-logs': {
      id: '/_app/admin/email-logs'
      path: '/email-logs'
      fullPath: '/admin/email-logs'
      preLoaderRoute: typeof AppAdminEmailLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/connection-logs': {
      id: '/_app/admin/connection-logs'
      path: '/connection-logs'
      fullPath: '/admin/connection-logs'
      preLoaderRoute: typeof AppAdminConnectionLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/api-keys': {
      id: '/_app/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AppAdminApiKeysRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/channels/$channelId/': {
      id: '/_app/channels/$channelId/'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId/'
      preLoaderRoute: typeof AppChannelsChannelIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/$channelId/settings': {
      id: '/_app/channels/$channelId/settings'
      path: '/channels/$channelId/settings'
      fullPath: '/channels/$channelId/settings'
      preLoaderRoute: typeof AppChannelsChannelIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/$channelId/chat/$contactNumber': {
      id: '/_app/channels/$channelId/chat/$contactNumber'
      path: '/channels/$channelId/chat/$contactNumber'
      fullPath: '/channels/$channelId/chat/$contactNumber'
      preLoaderRoute: typeof AppChannelsChannelIdChatContactNumberRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminApiKeysRoute: typeof AppAdminApiKeysRoute
  AppAdminConnectionLogsRoute: typeof AppAdminConnectionLogsRoute
  AppAdminEmailLogsRoute: typeof AppAdminEmailLogsRoute
  AppAdminEmailTransportsRoute: typeof AppAdminEmailTransportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSmsLogsRoute: typeof AppAdminSmsLogsRoute
  AppAdminSmsQueueRoute: typeof AppAdminSmsQueueRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWebhookLogsRoute: typeof AppAdminWebhookLogsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminApiKeysRoute: AppAdminApiKeysRoute,
  AppAdminConnectionLogsRoute: AppAdminConnectionLogsRoute,
  AppAdminEmailLogsRoute: AppAdminEmailLogsRoute,
  AppAdminEmailTransportsRoute: AppAdminEmailTransportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSmsLogsRoute: AppAdminSmsLogsRoute,
  AppAdminSmsQueueRoute: AppAdminSmsQueueRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWebhookLogsRoute: AppAdminWebhookLogsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDocsRoute: typeof AppDocsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppChannelsIndexRoute: typeof AppChannelsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppChannelsChannelIdSettingsRoute: typeof AppChannelsChannelIdSettingsRoute
  AppChannelsChannelIdIndexRoute: typeof AppChannelsChannelIdIndexRoute
  AppChannelsChannelIdChatContactNumberRoute: typeof AppChannelsChannelIdChatContactNumberRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDocsRoute: AppDocsRoute,
  AppProfileRoute: AppProfileRoute,
  AppChannelsIndexRoute: AppChannelsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppChannelsChannelIdSettingsRoute: AppChannelsChannelIdSettingsRoute,
  AppChannelsChannelIdIndexRoute: AppChannelsChannelIdIndexRoute,
  AppChannelsChannelIdChatContactNumberRoute:
    AppChannelsChannelIdChatContactNumberRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
