services:
  smpp:
    image: ghcr.io/santosh-rumsan/rumsan-smpp:latest
    ports:
      - "${HTTP_PORT:-9511}:9511"
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
